version: "3.9"

services:
  mysql-container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345"
      MYSQL_DATABASE: insurance-calc-db"
    ports:
      - "3000:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container