version: "3.9"

services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: insurance-calc-db
    ports:
      - "3000:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345"]
      interval: 5s
      timeout: 5s
      retries: 10

  insurance-calculator-app:
    container_name: insurance-calc-container
    image: insurance-calculator:1.0.3
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy